from pydantic import BaseModel, Field
from typing import List, Dict, Optional

class Suspect(BaseModel):
    name: str = Field(description="Name of the suspect.")
    means: str = Field(description="How they could have committed the crime.")
    motive: str = Field(description="Why they would want to commit the crime.")
    opportunity: str = Field(description="Their alibi or presence at the scene.")
    is_lying: bool = Field(default=False, description="Whether this suspect will lie in testimonies.")

class HiddenStoryDB(BaseModel):
    """
    Data structure to store the 'Ground Truth Constraints' generated by the Crime Creator.
    """
    victim: str = Field(description="Name of the victim.")
    killer: str = Field(description="Name of the actual killer.")
    true_motive: str = Field(description="The real reason the killer committed the crime.")
    weapon: str = Field(description="The weapon used to commit the murder.")
    timeline: List[str] = Field(description="Timeline of the killer's actions before, during, and after the crime.")
    suspects: List[Suspect] = Field(description="List of all plausible suspects including the killer and innocent parties.")
    red_herrings: List[str] = Field(description="Irrelevant clues meant to confuse the detective.")
    interference_plan: str = Field(description="How the killer is actively trying to hide their tracks or frame others.")

class SceneOutcome(BaseModel):
    """
    Raw scene outcome generated by the Investigation Generator.
    """
    plot_point_number: int = Field(description="The current step in the investigation (1-15+).")
    action_taken: str = Field(description="What the detective did in this scene.")
    obstacle_faced: str = Field(description="The challenge or confounding information the detective encountered.")
    outcome: str = Field(description="What happened and what was discovered or lost. Could be a success or failure.")
    suspense_element: str = Field(description="How time pressure or stakes were increased in this scene.")

class StateTracker(BaseModel):
    """
    System state dictionary tracking the ongoing investigation.
    """
    current_plot_count: int = Field(default=0, description="Number of plot points completed.")
    known_clues: List[str] = Field(default_factory=list, description="Clues the detective has found.")
    testimonies: Dict[str, str] = Field(default_factory=dict, description="Statements given by suspects.")
    remaining_time: int = Field(default=24, description="Hours left to solve the case.")
    completed_scenes: List[SceneOutcome] = Field(default_factory=list, description="History of outcomes.")
